
replicaCount: 1

image:
  repository: jscheel42/little-lookup
  tag: latest
  pullPolicy: Always

env: {}

db:
  path: "/data/default.db"

debug: false

service:
  type: ClusterIP
  port: 8088

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /
  hosts: []

persistence:
  enabled: false
  existingclaim: mypvc

resources:
  requests:
    memory: 128Mi
    cpu: 50m
  limits:
    memory: 512Mi
    cpu: 500m

nodeSelector: {}

tolerations: []

affinity: {}
