{{- if .Values.psk.enabled }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.psk.secretName }}
  labels:
    app: {{ template "little-lookup.name" . }}
    chart: {{ template "little-lookup.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  psk: {{ .Values.psk.value | b64enc | quote }}

{{- end }}