apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pgpassSecretName }}
  labels:
    app: {{ template "pg-push.name" . }}
    chart: {{ template "pg-push.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  .pgpass: |-
    {{ .Values.db.hostname }}:{{ .Values.db.port }}:{{ .Values.db.dbname }}:{{ .Values.db.username }}:{{ .Values.db.password }}
