apiVersion: v1
kind: Service
metadata:
  name: {{ template "pg-push.fullname" . }}
  labels:
    app: {{ template "pg-push.name" . }}
    chart: {{ template "pg-push.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
{{- if eq .Values.service.type "NodePort" }}
  type: NodePort
  ports:
    - port: 8088
      nodePort: {{ .Values.service.port }}
{{- else }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8088
      protocol: TCP
      name: http
{{- end }}
  selector:
    app: {{ template "pg-push.name" . }}
    release: {{ .Release.Name }}
